/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 grass.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

const Grass  = (props) =>{
  const { nodes, materials } = useGLTF('/grass.glb')

  const GoundTextureProps = useTexture({
    map: './textures/Stylized_Stone_Floor_005_basecolor.jpg', 
    // displacementMap: './textures/Stylized_Stone_Floor_005_height.jpg',
    normalMap: './textures/Stylized_Stone_Floor_005_normal.jpg',
    roughnessMap: './textures/Stylized_Stone_Floor_005_roughness.jpg',
    aoMap: './textures/Stylized_Stone_Floor_005_ambientOcclusion.jpg',
  })


  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.594, 0]} scale={0.9}>
        {/* <mesh geometry={nodes.Plano003.geometry} material={materials['Cesped Base']} /> */}
        <mesh geometry={nodes.Plano003.geometry} > 
          <meshStandardMaterial  {...GoundTextureProps} />
        </mesh>
        <mesh geometry={nodes.Plano003_1.geometry} material={materials['Tierra Base']} />
      </group>
    </group>
  )
}

useGLTF.preload('/grass.glb')

export default Grass;
