/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/red-with-wheel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Plant = (props) => {
  const { nodes, materials } = useGLTF('/red-with-wheel.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={14.407}>
        <mesh geometry={nodes.Bergenia_Rotblum_Set048.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.119, 0.243, -0.192]} rotation={[-Math.PI, 1.495, -Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set049.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.062, 0.241, -0.222]} rotation={[0, -0.762, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set050.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.077, 0.243, -0.408]} rotation={[0, -1.495, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set051.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.128, 0.243, -0.402]} rotation={[-Math.PI, 1.219, -Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set052.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.172, 0.369, -0.289]} rotation={[-Math.PI, 0.721, -Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set053.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.022, 0.367, -0.183]} rotation={[0, 0.011, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set054.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.118, 0.369, -0.306]} rotation={[0, -0.721, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set055.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.032, 0.369, -0.445]} rotation={[-Math.PI, 0.445, -Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set056.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.137, 0.501, -0.21]} rotation={[-Math.PI, 1.321, -Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set057.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.046, 0.498, -0.207]} rotation={[0, -0.588, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set058.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.093, 0.501, -0.388]} rotation={[0, -1.321, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set059.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.11, 0.501, -0.418]} rotation={[-Math.PI, 1.045, -Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set060.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.019, 0.631, -0.16]} rotation={[0, 0.91, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set061.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.096, 0.628, -0.304]} rotation={[0, -1.499, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set062.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.019, 0.631, -0.451]} rotation={[Math.PI, -0.91, Math.PI]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set063.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.167, 0.631, -0.309]} rotation={[0, 1.185, 0]} scale={0.145} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set065.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.031, 0.761, -0.261]} scale={0.169} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set067.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.098, 0.761, -0.261]} scale={0.169} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set069.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[0.098, 0.761, -0.404]} scale={0.169} />
        <mesh geometry={nodes.Bergenia_Rotblum_Set070.geometry} material={materials['Sunflower_sf1hcdvf2.002']} position={[-0.042, 0.761, -0.404]} scale={0.169} />
        <mesh geometry={nodes.Circle032.geometry} material={materials['Dry Soil.001']} position={[0.026, 0.631, -0.303]} rotation={[0, 1.562, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle033.geometry} material={materials['Material.005']} position={[0.025, 0.633, -0.303]} rotation={[0, 1.537, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle034.geometry} material={materials['Dry Soil.001']} position={[0.026, 0.501, -0.303]} rotation={[0, 0.867, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle035.geometry} material={materials['Dry Soil.001']} position={[0.026, 0.368, -0.303]} rotation={[0, 1.562, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle036.geometry} material={materials['Dry Soil.001']} position={[0.026, 0.237, -0.303]} rotation={[0, 0.704, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle037.geometry} material={materials['Dry Soil.001']} position={[0.026, 0.103, -0.303]} rotation={[0, 1.537, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle038.geometry} material={materials['Material.005']} position={[0.027, 0.503, -0.302]} rotation={[-Math.PI, 0.729, -Math.PI]} scale={[0.114, 0.103, 0.118]} />
        <mesh geometry={nodes.Circle039.geometry} material={materials['Material.005']} position={[0.025, 0.501, -0.302]} rotation={[-Math.PI, 0.691, -Math.PI]} scale={0.161} />
        <mesh geometry={nodes.Circle040.geometry} material={materials['Dry Soil.001']} position={[0.026, 0.372, -0.301]} rotation={[-Math.PI, 1.52, -Math.PI]} scale={[0.114, 0.103, 0.118]} />
        <mesh geometry={nodes.Circle041.geometry} material={materials['Material.005']} position={[0.03, 0.629, -0.303]} rotation={[0, -0.08, 0]} scale={0.095} />
        <mesh geometry={nodes.Circle042.geometry} material={materials['Material.005']} position={[0.025, 0.37, -0.303]} rotation={[0, 1.537, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle043.geometry} material={materials['Material.005']} position={[0.026, 0.232, -0.301]} rotation={[0, 0.776, 0]} scale={[0.114, 0.103, 0.118]} />
        <mesh geometry={nodes.Circle044.geometry} material={materials['Material.005']} position={[0.026, 0.237, -0.303]} rotation={[0, 0.691, 0]} scale={0.161} />
        <mesh geometry={nodes.Circle045.geometry} material={materials['Material.005']} position={[0.03, 0.368, -0.303]} rotation={[0, -0.08, 0]} scale={0.096} />
        <mesh geometry={nodes.Circle046.geometry} material={materials['Dry Soil']} position={[0.03, 0.106, -0.303]} rotation={[0, -0.08, 0]} scale={0.096} />
        <mesh geometry={nodes.Circle047.geometry} material={materials['Material.005']} position={[0.026, 0.105, -0.303]} rotation={[0, 1.556, 0]} scale={0.161} />
        <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-0.016, 0.115, -0.256]} rotation={[0, -0.759, -Math.PI]} scale={[-0.011, -0.003, -0.008]} />
        <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0.071, 0.118, -0.355]} rotation={[0, -0.731, 0]} scale={[0.011, 0.003, 0.008]} />
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[0.07, 0.115, -0.247]} rotation={[0, 0.695, -Math.PI]} scale={[-0.011, -0.003, -0.008]} />
        <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-0.02, 0.118, -0.349]} rotation={[0, 0.695, 0]} scale={[0.011, 0.003, 0.008]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-0.075, 0.127, 0.177]} scale={[0.007, 0.003, 0.007]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[0.127, 0.127, 0.156]} scale={[0.007, 0.003, 0.007]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.005']} position={[0.03, 0.123, 0.226]} scale={[0.171, 0.013, 0.171]} />
        <group position={[-0.079, 0.11, 0.145]} rotation={[0, -0.583, Math.PI]} scale={0.763}>
          <mesh geometry={nodes.Cylinder032.geometry} material={materials['caster_plastic touched.001']} />
          <mesh geometry={nodes.Cylinder032_1.geometry} material={materials['caster_plastic touched w.001']} />
        </group>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['caster_plastic touched.001']} position={[-0.079, 0.11, 0.145]} rotation={[0, -0.583, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['caster_plastic touched.001']} position={[-0.079, 0.11, 0.145]} rotation={[0, -0.583, Math.PI]} scale={0.763} />
        <group position={[0.125, 0.11, 0.147]} rotation={[0, 1.399, Math.PI]} scale={0.763}>
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['caster_plastic touched.001']} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['caster_plastic touched w.001']} />
        </group>
        <mesh geometry={nodes.Cylinder008.geometry} material={materials['caster_plastic touched.001']} position={[0.125, 0.11, 0.147]} rotation={[0, 1.399, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['caster_plastic touched.001']} position={[0.125, 0.11, 0.147]} rotation={[0, 1.399, Math.PI]} scale={0.763} />
        <group position={[0.024, 0.11, 0.315]} rotation={[0, 0, Math.PI]} scale={0.763}>
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['caster_plastic touched.001']} />
          <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['caster_plastic touched w.001']} />
        </group>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['caster_plastic touched.001']} position={[0.024, 0.11, 0.315]} rotation={[0, 0, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['caster_plastic touched.001']} position={[0.024, 0.11, 0.315]} rotation={[0, 0, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['caster_plastic touched.001']} position={[0.024, 0.11, 0.315]} rotation={[0, 0, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[0.019, 0.127, -0.216]} scale={[0.007, 0.003, 0.007]} />
        <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} position={[-0.075, 0.127, -0.35]} scale={[0.007, 0.003, 0.007]} />
        <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} position={[0.127, 0.127, -0.371]} scale={[0.007, 0.003, 0.007]} />
        <mesh geometry={nodes.Cylinder017.geometry} material={materials['Material.005']} position={[0.03, 0.123, -0.301]} scale={[0.171, 0.013, 0.171]} />
        <mesh geometry={nodes.Cylinder022.geometry} material={materials['caster_plastic touched.001']} position={[0.125, 0.11, 0.147]} rotation={[0, 1.399, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder026.geometry} material={materials['caster_plastic touched.001']} position={[-0.079, 0.11, 0.145]} rotation={[0, -0.583, Math.PI]} scale={0.763} />
        <group position={[0.027, 0.497, 0.226]} scale={[0.013, 0.371, 0.013]}>
          <mesh geometry={nodes.Cylinder033.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cylinder033_1.geometry} material={materials['Material.006']} />
        </group>
        <mesh geometry={nodes.Cylinder034.geometry} material={nodes.Cylinder034.material} position={[0.019, 0.127, 0.311]} scale={[0.007, 0.003, 0.007]} />
        <group position={[0.027, 0.497, -0.301]} scale={[0.013, 0.371, 0.013]}>
          <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cylinder012_2.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-0.079, 0.11, -0.382]} rotation={[0, -0.583, Math.PI]} scale={0.763}>
          <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['caster_plastic touched.001']} />
          <mesh geometry={nodes.Cylinder013_2.geometry} material={materials['caster_plastic touched w.001']} />
        </group>
        <mesh geometry={nodes.Cylinder038.geometry} material={materials['caster_plastic touched.001']} position={[-0.079, 0.11, -0.382]} rotation={[0, -0.583, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder039.geometry} material={materials['caster_plastic touched.001']} position={[-0.079, 0.11, -0.382]} rotation={[0, -0.583, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder040.geometry} material={materials['caster_plastic touched.001']} position={[-0.079, 0.11, -0.382]} rotation={[0, -0.583, Math.PI]} scale={0.763} />
        <group position={[0.125, 0.11, -0.38]} rotation={[0, 1.399, Math.PI]} scale={0.763}>
          <mesh geometry={nodes.Cylinder017_1.geometry} material={materials['caster_plastic touched.001']} />
          <mesh geometry={nodes.Cylinder017_2.geometry} material={materials['caster_plastic touched w.001']} />
        </group>
        <mesh geometry={nodes.Cylinder042.geometry} material={materials['caster_plastic touched.001']} position={[0.125, 0.11, -0.38]} rotation={[0, 1.399, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder043.geometry} material={materials['caster_plastic touched.001']} position={[0.125, 0.11, -0.38]} rotation={[0, 1.399, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder044.geometry} material={materials['caster_plastic touched.001']} position={[0.125, 0.11, -0.38]} rotation={[0, 1.399, Math.PI]} scale={0.763} />
        <group position={[0.024, 0.11, -0.212]} rotation={[0, 0, Math.PI]} scale={0.763}>
          <mesh geometry={nodes.Cylinder038_1.geometry} material={materials['caster_plastic touched.001']} />
          <mesh geometry={nodes.Cylinder038_2.geometry} material={materials['caster_plastic touched w.001']} />
        </group>
        <mesh geometry={nodes.Cylinder046.geometry} material={materials['caster_plastic touched.001']} position={[0.024, 0.11, -0.212]} rotation={[0, 0, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder047.geometry} material={materials['caster_plastic touched.001']} position={[0.024, 0.11, -0.212]} rotation={[0, 0, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder048.geometry} material={materials['caster_plastic touched.001']} position={[0.024, 0.11, -0.212]} rotation={[0, 0, Math.PI]} scale={0.763} />
        <mesh geometry={nodes.Cylinder054.geometry} material={nodes.Cylinder054.material} position={[0.027, 0.112, -0.3]} scale={[0.063, 0.005, 0.063]} />
      </group>
    </group>
  )
}

useGLTF.preload('/red-with-wheel.glb')

export default Plant