/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 flower.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.petals.geometry} material={nodes.petals.material} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} />
    </group>
  )
}

useGLTF.preload('/flower.glb')
